name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Cache Bun
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            ~/.bun/install/global
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - run: bun install
      - run: bun lint
      - run: bun test:types
      - run: bun build
      - run: bun test --coverage
      - uses: codecov/codecov-action@v3
